# Generated by Django 2.2.7 on 2020-04-23 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(default="['','']", max_length=30)),
                ('num_deck_card', models.IntegerField()),
                ('draw_break', models.CharField(default=False, max_length=6)),
                ('turn_flag', models.CharField(default=False, max_length=6)),
                ('pile', models.IntegerField()),
                ('num_of_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='player_game_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.CharField(default=False, max_length=6)),
                ('hand_cards', models.CharField(default='', max_length=800)),
                ('guno', models.CharField(default=False, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gamestart', models.BooleanField(default=False)),
                ('global_variabl', models.CharField(default='{"current": ["", ""], "deck": [["red", "0"], ["red", "1"], ["red", "2"], ["red", "3"], ["red", "4"], ["red", "5"], ["red", "6"], ["red", "7"], ["red", "8"], ["red", "9"], ["red", "o"], ["red", "r"], ["red", "+2"], ["yellow", "0"], ["yellow", "1"], ["yellow", "2"], ["yellow", "3"], ["yellow", "4"], ["yellow", "5"], ["yellow", "6"], ["yellow", "7"], ["yellow", "8"], ["yellow", "9"], ["yellow", "o"], ["yellow", "r"], ["yellow", "+2"], ["green", "0"], ["green", "1"], ["green", "2"], ["green", "3"], ["green", "4"], ["green", "5"], ["green", "6"], ["green", "7"], ["green", "8"], ["green", "9"], ["green", "o"], ["green", "r"], ["green", "+2"], ["blue", "0"], ["blue", "1"], ["blue", "2"], ["blue", "3"], ["blue", "4"], ["blue", "5"], ["blue", "6"], ["blue", "7"], ["blue", "8"], ["blue", "9"], ["blue", "o"], ["blue", "r"], ["blue", "+2"], ["black", "+4"], ["black", "+4"], ["black", "c"], ["black", "c"]], "shuffel_deck": [], "pile": 0, "turn": 0, "turn_num": 0, "turnflag": 0, "pt": 0}', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.rooms')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='game_state_op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state_db', models.CharField(default='{"current": ["", ""], "num_deck_card": 0, "draw_break": true, "turn_flag": 0, "pile": 0, "num_of_players": 0}', max_length=1500)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamestate', to='api.rooms')),
            ],
        ),
    ]
